export const SEARCH_SESSIONS_SUCCEEDED = 'SEARCH_SESSIONS_SUCCEEDED';
export const SEARCH_SESSIONS_FAILED = 'SEARCH_SESSIONS_FAILED';
export const SEARCH_DAY = 'SEARCH_DAY';
export const UPDATE_DAY_SELECTION = 'UPDATE_DAY_SELECTION';

export const OPEN_SESSION_MODAL = 'OPEN_SESSION_MODAL';
export const CLOSE_SESSION_MODAL = 'CLOSE_SESSION_MODAL';

export const UPDATE_SESSION_CLIENT = 'UPDATE_SESSION_CLIENT';
export const UPDATE_SESSION_SERVICE = 'UPDATE_SESSION_SERVICE';
export const UPDATE_SESSION_DAY = 'UPDATE_SESSION_DAY';
export const UPDATE_SESSION_START_TIME = 'UPDATE_SESSION_START_TIME';
export const UPDATE_SESSION_END_TIME = 'UPDATE_SESSION_END_TIME';
export const UPDATE_SESSION_NOTES = 'UPDATE_SESSION_NOTES';
export const UPDATE_SESSION_LOCATION = 'UPDATE_SESSION_LOCATION';

export const SAVE_SESSION_FAILED = 'SAVE_SESSION_FAILED';