export const SEARCH_SESSIONS_SUCCEEDED = 'SEARCH_SESSIONS_SUCCEEDED';
export const SEARCH_SESSIONS_FAILED = 'SEARCH_SESSIONS_FAILED';
export const SEARCH_DAY = 'SEARCH_DAY';
export const UPDATE_DAY_SELECTION = 'UPDATE_DAY_SELECTION';
export const OPEN_SESSION_MODAL = 'OPEN_SESSION_MODAL';
export const CLOSE_SESSION_MODAL = 'CLOSE_SESSION_MODAL';