export const ADD_CLIENT_SUCCEEDED = 'ADD_CLIENT_SUCCEEDED';
export const ADD_CLIENT_FAILED = 'ADD_CLIENT_FAILED';

export const OPEN_NEW_CLIENT_MODAL = 'OPEN_NEW_CLIENT_MODAL';
export const CLOSE_NEW_CLIENT_MODAL = 'CLOSE_NEW_CLIENT_MODAL';

export const SEARCH_CLIENTS_SUCCEEDED = 'SEARCH_CLIENTS_SUCCEEDED';
export const SEARCH_CLIENTS_FAILED = 'SEARCH_CLIENTS_FAILED';

export const UPDATE_NEW_CLIENT_NAME = 'UPDATE_NEW_CLIENT_NAME';