export const ARCHIVE_CLIENT_SUCCEEDED = 'ARCHIVE_CLIENT_SUCCEEDED';
export const ARCHIVE_CLIENT_FAILED = 'ARCHIVE_CLIENT_FAILED';

export const OPEN_CLIENT_MODAL = 'OPEN_CLIENT_MODAL';
export const CLOSE_CLIENT_MODAL = 'CLOSE_CLIENT_MODAL';
export const OPEN_ARCHIVE_MODAL = 'OPEN_CLIENT_ARCHIVE_MODAL';
export const CLOSE_ARCHIVE_MODAL= 'CLOSE_CLIENT_ARCHIVE_MODAL';

export const SAVE_CLIENT_SUCCEEDED = 'SAVE_CLIENT_SUCCEEDED';
export const SAVE_CLIENT_FAILED = 'SAVE_CLIENT_FAILED';

export const SEARCH_CLIENTS_SUCCEEDED = 'SEARCH_CLIENTS_SUCCEEDED';
export const SEARCH_CLIENTS_FAILED = 'SEARCH_CLIENTS_FAILED';

export const UPDATE_CLIENT_NAME = 'UPDATE_CLIENT_NAME';
export const UPDATE_CLIENT_PHONE = 'UPDATE_CLIENT_PHONE';
export const UPDATE_CLIENT_EMAIL = 'UPDATE_CLIENT_EMAIL';