export const SEARCH_SERVICES_SUCCEEDED = 'SEARCH_SERVICES_SUCCEEDED';
export const SEARCH_SERVICES_FAILED = 'SEARCH_SERVICES_FAILED';

export const ARCHIVE_SERVICE_SUCCEEDED = 'ARCHIVE_SERVICE_SUCCEEDED';
export const ARCHIVE_SERVICE_FAILED = 'ARCHIVE_SERVICE_FAILED';

export const OPEN_SERVICE_MODAL = 'OPEN_SERVICE_MODAL';
export const CLOSE_SERVICE_MODAL = 'CLOSE_SERVICE_MODAL';

export const OPEN_ARCHIVE_MODAL = 'OPEN_SERVICE_ARCHIVE_MODAL';
export const CLOSE_ARCHIVE_MODAL= 'CLOSE_SERVICE_ARCHIVE_MODAL';

export const SAVE_SERVICE_SUCCEEDED = 'SAVE_SERVICE_SUCCEEDED';
export const SAVE_SERVICE_FAILED = 'SAVE_SERVICE_FAILED';

export const UPDATE_SERVICE_TITLE = 'UPDATE_SERVICE_TITLE';
export const UPDATE_SERVICE_DURATION = 'UPDATE_SERVICE_DURATION';