
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const NULLIFY_TOKEN = 'NULLIFY_TOKEN';

export const SEARCH_CLIENTS_SUCCEEDED = 'SEARCH_CLIENTS_SUCCEEDED';
export const SEARCH_CLIENTS_FAILED = 'SEARCH_CLIENTS_FAILED';

export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';